# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jan/Desktop/K-Means-Clustering-CUDA

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jan/Desktop/K-Means-Clustering-CUDA

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jan/Desktop/K-Means-Clustering-CUDA/CMakeFiles /home/jan/Desktop/K-Means-Clustering-CUDA//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jan/Desktop/K-Means-Clustering-CUDA/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mainCudaApp

# Build rule for target.
mainCudaApp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mainCudaApp
.PHONY : mainCudaApp

# fast build rule for target.
mainCudaApp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainCudaApp.dir/build.make CMakeFiles/mainCudaApp.dir/build
.PHONY : mainCudaApp/fast

src/k_means_cpu.o: src/k_means_cpu.cu.o
.PHONY : src/k_means_cpu.o

# target to build an object file
src/k_means_cpu.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainCudaApp.dir/build.make CMakeFiles/mainCudaApp.dir/src/k_means_cpu.cu.o
.PHONY : src/k_means_cpu.cu.o

src/k_means_cpu.i: src/k_means_cpu.cu.i
.PHONY : src/k_means_cpu.i

# target to preprocess a source file
src/k_means_cpu.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainCudaApp.dir/build.make CMakeFiles/mainCudaApp.dir/src/k_means_cpu.cu.i
.PHONY : src/k_means_cpu.cu.i

src/k_means_cpu.s: src/k_means_cpu.cu.s
.PHONY : src/k_means_cpu.s

# target to generate assembly for a file
src/k_means_cpu.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainCudaApp.dir/build.make CMakeFiles/mainCudaApp.dir/src/k_means_cpu.cu.s
.PHONY : src/k_means_cpu.cu.s

src/kernel.o: src/kernel.cu.o
.PHONY : src/kernel.o

# target to build an object file
src/kernel.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainCudaApp.dir/build.make CMakeFiles/mainCudaApp.dir/src/kernel.cu.o
.PHONY : src/kernel.cu.o

src/kernel.i: src/kernel.cu.i
.PHONY : src/kernel.i

# target to preprocess a source file
src/kernel.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainCudaApp.dir/build.make CMakeFiles/mainCudaApp.dir/src/kernel.cu.i
.PHONY : src/kernel.cu.i

src/kernel.s: src/kernel.cu.s
.PHONY : src/kernel.s

# target to generate assembly for a file
src/kernel.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainCudaApp.dir/build.make CMakeFiles/mainCudaApp.dir/src/kernel.cu.s
.PHONY : src/kernel.cu.s

src/pt.o: src/pt.cu.o
.PHONY : src/pt.o

# target to build an object file
src/pt.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainCudaApp.dir/build.make CMakeFiles/mainCudaApp.dir/src/pt.cu.o
.PHONY : src/pt.cu.o

src/pt.i: src/pt.cu.i
.PHONY : src/pt.i

# target to preprocess a source file
src/pt.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainCudaApp.dir/build.make CMakeFiles/mainCudaApp.dir/src/pt.cu.i
.PHONY : src/pt.cu.i

src/pt.s: src/pt.cu.s
.PHONY : src/pt.s

# target to generate assembly for a file
src/pt.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainCudaApp.dir/build.make CMakeFiles/mainCudaApp.dir/src/pt.cu.s
.PHONY : src/pt.cu.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... mainCudaApp"
	@echo "... src/k_means_cpu.o"
	@echo "... src/k_means_cpu.i"
	@echo "... src/k_means_cpu.s"
	@echo "... src/kernel.o"
	@echo "... src/kernel.i"
	@echo "... src/kernel.s"
	@echo "... src/pt.o"
	@echo "... src/pt.i"
	@echo "... src/pt.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

