#pragma once

#define NUM_POINTS 1 << 21
#define NUM_FEATURES 5
#define NUM_CLUSTERS 8
#define NUM_EPOCHES 5

#define MEASURE_TIME 0
#define RUN_REDUCE_FEATURE_WISE 1
#define SYNCHRONIZE_AFTER_KERNEL_RUN 0
 

 #define DEBUG_PROGRAM 0
 #define DEBUG_GPU_ITERATION 0